
services:
  mosquitto:
    container_name: mosquitto1
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto1.conf:/mosquitto/config/mosquitto.conf

  nodered:
    container_name: nodered1
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered_data1:/data
    depends_on:
      - mosquitto

  influxdb:
    container_name: influxdb-server1
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data1:/var/lib/influxdb

  grafana:
    container_name: grafana1
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data1:/var/lib/grafana


volumes:
  nodered_data1:
  influxdb_data1:
  grafana_data1:
